services:
  app:
    build: .
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
  caddy:
    image: caddy:alpine
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    restart: unless-stopped
    environment:
      DOMAIN: ${DOMAIN:-localhost}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - /var/log/caddy/:/var/log/caddy/
volumes:
  caddy_data:
  caddy_config:
